spring:
  cloud:
    function:
      definition: output
    stream:
      bindings:
        output:
          destination: organization-events
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
